### ISSUE TITLE
使用 Telnet 作為 Connect Mode 時會發生錯誤

### ISSUE THREAD

**Issue by PichuChen** [PttCodingMan/PyPtt#70]
測試環境 macOS 10.15.7, Python 3.9.0
測試版本 master branch (cc8b2ad523a3922045443f3f910cf0519f8303ce)

測試程式碼
```
from PyPtt import PTT

if __name__ == '__main__':
	print('test')
	ptt_bot = PTT.API(
		log_level=PTT.log.level.DEBUG,
		connect_mode=PTT.connect_core.connect_mode.TELNET
		)
```

出現訊息
```
test
PyPtt v 0.9.39
Developed by CodingMan
[1212 00:45:10][資訊] 繁體中文語言模組 [初始化]
Traceback (most recent call last):
  File "/Users/tih/localgitrepos/PyPtt/./pichu_test.py", line 9, in <module>
    ptt_bot = PTT.API(
  File "/Users/tih/localgitrepos/PyPtt/PyPtt/PTT.py", line 142, in __init__
    raise ValueError('[PyPtt] Unknown connect_mode', connect_mode)
ValueError: ('[PyPtt] Unknown connect_mode', 1)
```

Telnet 是 1, Websocket 是 2 那這樣預設的0是？

**Comment by PichuChen** [comment]
看起來是在 connect_core.py 那邊的 min_value 限制住了，如果需要測試的話可以把 WEBSOCKET 改為 TELNET 即可。

**Comment by PttCodingMan** [comment]
此改動是因為站方要求關閉 telnet 連線
最近官方已經直接移除 Telnet 連線方式

https://www.ptt.cc/bbs/SYSOP/M.1649953913.A.02D.html
