### ISSUE TITLE
特定簽名檔會造成使用寄信功能後無法正常使用其他功能

### ISSUE THREAD

**Issue by GniN** [PttCodingMan/PyPtt#78]
#### Issue description
使用者如果有特定的簽名檔，使用寄信功能後就無法正常使用其他的功能。

#### Steps to reproduce
1. 新增簽名檔，簽名檔內容請見remarks # 2，簽名檔位置必須在第一個 (寄信時選擇簽名檔的時候才會出現在預覽第一頁)。
2. 使用PyPtt任意寄兩封信給任意收件人(可以是自己)
```python
from PyPtt import PTT
ptt_bot = PTT.API(log_level=PTT.log.level.TRACE)

try:
    ptt_bot.login('ptt_id', '*******')
except PTT.exceptions.LoginError:
    ptt_bot.log('登入失敗')
    sys.exit()

receiver = 'receiver_ptt_id'

# 第一封會成功寄出
ptt_bot.mail(receiver, '測試標題', '內文', 1, False)
# 第二封會失敗
ptt_bot.mail(receiver, '測試標題', '內文', 1, False)
```

#### Remarks
1. 新增簽名檔的路徑為【 個人設定區 】=> 【個人檔案】 (名片,簽名檔...) => 編輯簽名檔
2. 會出現問題的簽名檔請至看板:turtlesoup 文章ID: #1V-lEn00 抓取，似乎因為簽名檔含有控制碼，直接貼上來會變亂碼，要麻煩您用比較麻煩的方式抓測試資料 

#### What's the expected result?
- 範例程式碼的兩封信都應該成功寄出

#### What's the actual result?
- 只有第一封信寄出，第二封信會失敗

#### Additional details / screenshot
- 本來猜測可能是特定的控制碼或特殊字元造成的問題，但把簽名檔拆成一行一行分批測都正常，不知道是不是跟長度有關。
- 使用版本: PyPtt v 0.9.41
- 寄第一封信的時候出現兩次選擇簽名檔，所以指令[b'1\r\x0c']被多傳了一次
```
[0222 12:33:09][資訊] 批踢踢訊息 [選擇 1th 簽名檔]
[0222 12:33:10][資訊] 批踢踢訊息 [選擇 1th 簽名檔]
```
- Trace logs
```
[0222 21:41:53][資訊] PyPtt v 0.9.41 [初始化]
(省略)
--------------------------------------------------
【 站內寄信 】
請輸入使用者代號: hsuan0904
主題：




《個人名片》hsuan0904 目前沒有名片
len:123
--------------------------------------------------
[0222 12:33:08][資訊] 批踢踢訊息 [開始寄信]
[0222 12:33:08][除錯] 花費時間 [0.395]
[0222 12:33:08][除錯] 送出訊息 [b'\xb4\xfa\xb8\xd5\xbc\xd0\xc3D\r\xa4\xba\xa4\xe5\x18\x0c']
--------------------------------------------------
【 檔案處理 】
[S/V]發信 (T)改標題 (A)放棄 (E)繼續 (R/W/D)讀寫刪暫存檔
確定要儲存檔案嗎？

注意：您即將 寄出 私人信件
len:78
--------------------------------------------------
[0222 12:33:08][資訊] 批踢踢訊息 [儲存檔案]
[0222 12:33:08][除錯] 花費時間 [0.3]
[0222 12:33:08][除錯] 送出訊息 [b's\r\x0c']
--------------------------------------------------
請選擇簽名檔 (1-9, 0=不加 x=隨機)[1]:     

【 簽名檔.1 】
      ▁▂▃▃▂▁       。─‧─。─‧─。─‧─。─‧─。─‧─。─‧─。┐
  ▅▆▇▇▆▅   │？◥◣?◢◤？他是人嗎？？？？？？？？  ◣？？ ？‧
  ▍▆▄▂  ▂▄▆▋   ‧？？◥ ◤ ？？？？？？？有人死亡嗎？   ◥◣？ ？│
                     │？？？   ？？？？？？？？？？？？？？  ？◥◣ ？。
    ◣  海 龜 湯  ◢=PTT=[44
len:257
--------------------------------------------------
[0222 12:33:09][資訊] 批踢踢訊息 [選擇 1th 簽名檔]
[0222 12:33:09][除錯] 花費時間 [1.304]
[0222 12:33:09][除錯] 送出訊息 [b'1\r\x0c']
--------------------------------------------------
m     。？？？  ？？有非現實要素嗎？？？？？？ ？？◥ ？│
      ▆▄──▄▆       └‧─。─‧─。─‧─。─‧─。─‧─。─‧─。─‧
len:84
--------------------------------------------------
--------------------------------------------------
請選擇簽名檔 (1-9, 0=不加 x=隨機)[1]: 1   

【 簽名檔.1 】
      ▁▂▃▃▂▁       。─‧─。─‧─。─‧─。─‧─。─‧─。─‧─。┐
  ▅▆▇▇▆▅   │？◥◣?◢◤？他是人嗎？？？？？？？？  ◣？？ ？‧
  ▍▆▄▂  ▂▄▆▋   ‧？？◥ ◤ ？？？？？？？有人死亡嗎？   ◥◣？ ？│
                     │？？？   ？？？？？？？？？？？？？？  ？◥◣ ？。
    ◣  海 龜 湯  ◢=PTT=[44
len:257
--------------------------------------------------
[0222 12:33:10][資訊] 批踢踢訊息 [選擇 1th 簽名檔]
[0222 12:33:10][除錯] 花費時間 [0.305]
[0222 12:33:10][除錯] 送出訊息 [b'1\r\x0c']
--------------------------------------------------
m     。？？？  ？？有非現實要素嗎？？？？？？ ？？◥ ？│
      ▆▄──▄▆       └‧─。─‧─。─‧─。─‧─。─‧─。─‧─。─‧




















 已順利寄出，是否自存底稿(Y/N)？[N]
len:136
--------------------------------------------------
[0222 12:33:10][資訊] 批踢踢訊息 [放棄自存底稿]
[0222 12:33:10][除錯] 花費時間 [0.005]
[0222 12:33:10][除錯] 送出訊息 [b'n\r\x0c']
--------------------------------------------------























  ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ 請按任意鍵繼續 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
len:66
--------------------------------------------------
[0222 12:33:10][資訊] 批踢踢訊息 [請按任意鍵繼續]
[0222 12:33:10][除錯] 花費時間 [0.297]
[0222 12:33:10][資訊] 寄信 [成功]
[0222 12:33:10][除錯] 送出訊息 [b' \x1bOD\x1bOD\x1bOD\x1bOD\x1bODT\rQ\rhsuan0904\r\x0c']
--------------------------------------------------
【 站內寄信 】
請輸入使用者代號:
len:51
--------------------------------------------------
--------------------------------------------------
【 站內寄信 】
請輸入使用者代號:
len:51
--------------------------------------------------
--------------------------------------------------
【 站內寄信 】
請輸入使用者代號: hsuan0904
主題：




《個人名片》hsuan0904 目前沒有名片
len:123
--------------------------------------------------
Traceback (most recent call last):
  File "money_giver.py", line 21, in <module>
    ptt_bot.mail(u, '測試標題', '內文', 1, False)
  File "***\Python38-32\lib\site-packages\PyPtt\PTT.py", line 1369, in mail
    return self._get_user(user_id)
  File "***\Python38-32\lib\site-packages\PyPtt\PTT.py", line 1208, in _get_user
    return _api_get_user.get_user(self, user_id)
  File "***\Python38-32\lib\site-packages\PyPtt\_api_get_user.py", line 133, in get_user
    login_time = int(data[2])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by PttCodingMan** [comment]
好的，我來處理

**Comment by PttCodingMan** [comment]
已經修好囉!!!

![image](https://user-images.githubusercontent.com/59732316/111289960-a0676a80-8680-11eb-93f3-cb32ff4a6c51.png)

我還會需要修其他問題才會一起推上 PyPi，如果急的話就直接拿 Github 的版本試試看吧
主因是寄信後，使用回到主選單的指令沒有作用，不知道是不是最近更新的關係 @@

改成 Enter 就可以了

修正請參考:
https://github.com/PttCodingMan/PyPtt/commit/cb707f724a683e90245e93decf3a311f3a3c3de5
